"""Render de los artefactos spec-driven (.aido/) al worktree y filtro compartido del diff.

Materializa constitución, spec y tareas como Markdown generado dentro del worktree del developer
(la BD es la fuente de verdad; los archivos son renders con encabezado explícito) para que viajen en
el PR y los runtimes CLI los lean del disco. El prefijo ``.aido/`` queda EXCLUIDO del cálculo de
``changedFiles`` — guard compartido con ``delivery.technical_lead_gate`` — porque ese campo es la
detección de no-op del loop: un run cuyo único cambio son estos renders no es trabajo real y debe
seguir bloqueando. El directorio del spec es estable por hilo (slug + sha corto del thread id), sin
contadores compartidos: hilos paralelos del mismo proyecto nunca colisionan.

@author Rodrigo Mason
"""

from __future__ import annotations

import hashlib
import re
from pathlib import Path
from typing import Any

AIDO_ARTIFACT_PREFIX = ".aido/"
GENERATED_HEADER = "<!-- generated by AIDO - the control plane database is the source of truth -->"
_SLUG_MAX_CHARS = 32


def is_aido_artifact_path(path: str) -> bool:
    """Indica si la ruta pertenece a los renders spec-driven (prefijo ``.aido/``)."""
    normalized = str(path or "").replace("\\", "/")
    while normalized.startswith("./"):
        normalized = normalized[2:]
    return normalized.startswith(AIDO_ARTIFACT_PREFIX) or normalized == AIDO_ARTIFACT_PREFIX.rstrip("/")


def exclude_aido_artifacts(paths: list[str]) -> list[str]:
    """Filtra los renders ``.aido/`` de una lista de rutas cambiadas (guard de no-op del loop)."""
    return [path for path in paths if not is_aido_artifact_path(path)]


def spec_dir_slug(thread_id: str, title: str) -> str:
    """Nombre estable del directorio de spec del hilo: slug del título + sha corto del thread id.

    Determinista y libre de carreras: no consume contadores compartidos, así que hilos paralelos del
    mismo proyecto obtienen directorios distintos y los mensajes siguientes del mismo hilo reusan el
    mismo (requisito de ampliación, no sobrescritura).
    """
    slug = re.sub(r"[^a-z0-9]+", "-", str(title or "spec").lower()).strip("-")[:_SLUG_MAX_CHARS] or "spec"
    digest = hashlib.sha1(str(thread_id or "").encode("utf-8")).hexdigest()[:8]
    return f"{slug}-{digest}"


def render_constitution_md(constitution: dict[str, Any]) -> str:
    """Render de solo lectura de la constitución; el hash permite detectar ediciones locales."""
    lines = [
        GENERATED_HEADER,
        f"<!-- version: {constitution.get('version')} content-hash: {constitution.get('contentHash')} -->",
        "",
        f"# {constitution.get('title') or 'Project constitution'}",
        "",
    ]
    lines.extend(f"- {principle}" for principle in constitution.get("principles") or [])
    non_negotiables = constitution.get("nonNegotiables") or []
    if non_negotiables:
        lines.extend(["", "## Non-negotiables", ""])
        lines.extend(f"- {item}" for item in non_negotiables)
    return "\n".join(lines) + "\n"


def render_spec_md(
    *,
    title: str,
    brief: dict[str, Any],
    stories: list[dict[str, Any]],
    acceptance_criteria: list[dict[str, Any]],
) -> str:
    """Render del QUÉ: brief + historias con sus criterios, listo para revisarse en el PR."""
    lines = [GENERATED_HEADER, "", f"# Spec: {title}", ""]
    for label, key in (
        ("Summary", "summary"),
        ("Problem", "problemStatement"),
        ("Scope", "scope"),
        ("Out of scope", "outOfScope"),
    ):
        value = str(brief.get(key) or "").strip()
        if value:
            lines.extend([f"## {label}", "", value, ""])
    goals = [str(goal) for goal in brief.get("goals") or []]
    if goals:
        lines.extend(["## Goals", ""])
        lines.extend(f"- {goal}" for goal in goals)
        lines.append("")
    criteria_by_story: dict[str, list[dict[str, Any]]] = {}
    for criterion in acceptance_criteria:
        criteria_by_story.setdefault(str(criterion.get("storyId")), []).append(criterion)
    if stories:
        lines.extend(["## User stories", ""])
        for story in stories:
            lines.append(f"### {story.get('title')}")
            as_a, i_want, so_that = story.get("asA"), story.get("iWant"), story.get("soThat")
            if as_a or i_want or so_that:
                lines.append(f"As a {as_a}, I want {i_want}, so that {so_that}.")
            story_criteria = sorted(
                criteria_by_story.get(str(story.get("id")), []),
                key=lambda item: int(item.get("sequence") or 0),
            )
            if story_criteria:
                lines.append("")
                lines.extend(f"- [ ] {criterion.get('criterion')}" for criterion in story_criteria)
            lines.append("")
    return "\n".join(lines) + "\n"


def render_tasks_md(tasks: list[dict[str, Any]], dependencies: list[dict[str, Any]]) -> str:
    """Render de las tareas técnicas por rol con sus dependencias explícitas."""
    depends_on: dict[str, list[str]] = {}
    for dependency in dependencies:
        depends_on.setdefault(str(dependency.get("taskId")), []).append(
            str(dependency.get("dependsOnTaskId"))
        )
    titles = {str(task.get("id")): str(task.get("title") or task.get("id")) for task in tasks}
    lines = [GENERATED_HEADER, "", "# Tasks", ""]
    for task in tasks:
        task_id = str(task.get("id"))
        lines.append(f"- [ ] **{task.get('role')}** — {task.get('title')}")
        lines.extend(
            f"  - depends on: {titles.get(upstream, upstream)}" for upstream in depends_on.get(task_id, [])
        )
    return "\n".join(lines) + "\n"


def write_spec_artifacts(
    workspace_path: str,
    *,
    thread_id: str,
    title: str,
    constitution: dict[str, Any] | None,
    brief: dict[str, Any] | None,
    stories: list[dict[str, Any]],
    acceptance_criteria: list[dict[str, Any]],
    tasks: list[dict[str, Any]],
    task_dependencies: list[dict[str, Any]],
) -> dict[str, Any]:
    """Escribe los renders al worktree y devuelve el directorio de spec + rutas relativas escritas.

    Solo escribe dentro de ``workspace_path`` (el worktree aislado del run, nunca la raíz del
    proyecto: escribir ahí dejaría el árbol base sucio y bloquearía todos los runs siguientes).
    """
    root = Path(workspace_path).resolve(strict=False)
    written: list[str] = []
    if constitution:
        memory_dir = root / ".aido" / "memory"
        memory_dir.mkdir(parents=True, exist_ok=True)
        (memory_dir / "constitution.md").write_text(
            render_constitution_md(constitution), encoding="utf-8", newline="\n"
        )
        written.append(".aido/memory/constitution.md")
    spec_dir_name = spec_dir_slug(thread_id, title)
    spec_dir = root / ".aido" / "specs" / spec_dir_name
    if brief or stories:
        spec_dir.mkdir(parents=True, exist_ok=True)
        (spec_dir / "spec.md").write_text(
            render_spec_md(
                title=title,
                brief=brief or {},
                stories=stories,
                acceptance_criteria=acceptance_criteria,
            ),
            encoding="utf-8",
            newline="\n",
        )
        written.append(f".aido/specs/{spec_dir_name}/spec.md")
    if tasks:
        spec_dir.mkdir(parents=True, exist_ok=True)
        (spec_dir / "tasks.md").write_text(
            render_tasks_md(tasks, task_dependencies), encoding="utf-8", newline="\n"
        )
        written.append(f".aido/specs/{spec_dir_name}/tasks.md")
    return {"specDir": f".aido/specs/{spec_dir_name}", "files": written}
