"""Bootstrap determinista del equipo base de agentes sobre perfiles operacionales.

El roster base vive en ``agent_profiles`` porque esos perfiles ya son el contrato usado por
runs, permisos, skills, limites de costo y UI. El bootstrap solo se activa cuando no hay
perfiles activos, de modo que una base nueva queda operable sin duplicar registros existentes.

@author Rodrigo Mason
"""

from __future__ import annotations

import sqlite3
from typing import Any

from .repository import AgentsRepository

BASE_TEAM_PROFILES: tuple[dict[str, Any], ...] = (
    {
        "id": "base-aido-lead",
        "name": "AIDO Lead / Coordinator",
        "role": "aido_lead",
        "runtimeMode": "hybrid",
        "allowedProviders": ["claude_code_cli", "codex_cli", "openai_compatible"],
        "allowedRuntimes": ["cli", "api"],
        "allowedTools": ["policy.evaluate", "evidence.create", "mcp"],
        "allowedSkills": ["architecture-software", "engineering-standards", "git-workflow"],
        "permissionProfile": "plan",
        "maxCostPerRun": 6.0,
        "maxTokensPerRun": 120000,
        "maxRuntimeSeconds": 900,
        "requiresApprovalOverUsd": 3.0,
        "qualityGates": ["plan_review", "risk_review", "handoff_review"],
        "defaultRuntimePolicy": {
            "providerCandidates": ["claude_code_cli", "codex_cli", "openai_compatible"],
            "requiredCapabilities": ["chat"],
            "selection": "first_executable",
            "fallback": "blocked_with_reason",
        },
        "reviewerPolicy": {"mode": "gated", "reviewerRole": "technical_lead"},
    },
    {
        "id": "base-product-owner",
        "name": "Product Owner",
        "role": "product_owner",
        "runtimeMode": "hybrid",
        "allowedProviders": ["claude_code_cli", "openai_compatible", "nvidia_nim"],
        "allowedRuntimes": ["cli", "api"],
        "allowedTools": ["evidence.create", "mcp"],
        "allowedSkills": ["product-spec", "brainstorming"],
        "permissionProfile": "plan",
        "maxCostPerRun": 4.0,
        "maxTokensPerRun": 100000,
        "maxRuntimeSeconds": 900,
        "requiresApprovalOverUsd": 2.0,
        "qualityGates": ["brief_review", "acceptance_criteria"],
        "defaultRuntimePolicy": {
            "providerCandidates": ["claude_code_cli", "openai_compatible", "nvidia_nim"],
            "requiredCapabilities": ["chat"],
            "selection": "first_executable",
            "fallback": "blocked_with_reason",
        },
        "reviewerPolicy": {"mode": "peer", "reviewerRole": "aido_lead"},
    },
    {
        "id": "base-project-manager",
        "name": "Project Manager",
        "role": "project_manager",
        "runtimeMode": "hybrid",
        "allowedProviders": ["openai_compatible", "ollama"],
        "allowedRuntimes": ["api", "ollama"],
        "allowedTools": ["evidence.create"],
        "allowedSkills": ["planning"],
        "permissionProfile": "plan",
        "maxCostPerRun": 1.5,
        "maxTokensPerRun": 60000,
        "maxRuntimeSeconds": 600,
        "requiresApprovalOverUsd": 1.0,
        "qualityGates": ["schedule_review"],
        "defaultRuntimePolicy": {
            "providerCandidates": ["openai_compatible", "ollama"],
            "requiredCapabilities": ["chat"],
            "selection": "first_executable",
            "fallback": "blocked_with_reason",
        },
        "reviewerPolicy": {"mode": "peer", "reviewerRole": "aido_lead"},
    },
    {
        "id": "base-scrum-master",
        "name": "Scrum Master",
        "role": "scrum_master",
        "runtimeMode": "hybrid",
        "allowedProviders": ["openai_compatible", "ollama"],
        "allowedRuntimes": ["api", "ollama"],
        "allowedTools": ["evidence.create"],
        "allowedSkills": ["planning"],
        "permissionProfile": "plan",
        "maxCostPerRun": 1.0,
        "maxTokensPerRun": 50000,
        "maxRuntimeSeconds": 600,
        "requiresApprovalOverUsd": 1.0,
        "qualityGates": ["flow_review"],
        "defaultRuntimePolicy": {
            "providerCandidates": ["openai_compatible", "ollama"],
            "requiredCapabilities": ["chat"],
            "selection": "first_executable",
            "fallback": "blocked_with_reason",
        },
        "reviewerPolicy": {"mode": "peer", "reviewerRole": "project_manager"},
    },
    {
        "id": "base-architect",
        "name": "Architect",
        "role": "architect",
        "runtimeMode": "hybrid",
        "allowedProviders": ["claude_code_cli", "openai_compatible", "nvidia_nim"],
        "allowedRuntimes": ["cli", "api"],
        "allowedTools": ["evidence.create", "policy.evaluate", "mcp"],
        "allowedSkills": ["architecture-software", "architecture-web", "engineering-standards"],
        "permissionProfile": "plan",
        "maxCostPerRun": 8.0,
        "maxTokensPerRun": 160000,
        "maxRuntimeSeconds": 900,
        "requiresApprovalOverUsd": 4.0,
        "qualityGates": ["architecture_review", "risk_register", "adr_required"],
        "defaultRuntimePolicy": {
            "providerCandidates": ["claude_code_cli", "openai_compatible", "nvidia_nim"],
            "requiredCapabilities": ["chat"],
            "selection": "first_executable",
            "fallback": "blocked_with_reason",
        },
        "reviewerPolicy": {"mode": "gated", "reviewerRole": "technical_lead"},
    },
    {
        "id": "base-technical-lead",
        "name": "Technical Lead",
        "role": "technical_lead",
        "runtimeMode": "hybrid",
        "allowedProviders": ["claude_code_cli", "codex_cli", "openai_compatible"],
        "allowedRuntimes": ["cli", "api"],
        "allowedTools": ["shell", "workspace_patch", "policy.evaluate", "evidence.create"],
        "allowedSkills": ["engineering-standards", "test-driven-development"],
        "permissionProfile": "dev_safe",
        "maxCostPerRun": 6.0,
        "maxTokensPerRun": 140000,
        "maxRuntimeSeconds": 900,
        "requiresApprovalOverUsd": 3.0,
        "qualityGates": ["lint", "test", "typecheck", "review"],
        "defaultRuntimePolicy": {
            "providerCandidates": ["claude_code_cli", "codex_cli", "openai_compatible"],
            "requiredCapabilities": ["chat"],
            "selection": "first_executable",
            "fallback": "blocked_with_reason",
        },
        "reviewerPolicy": {"mode": "peer", "reviewerRole": "aido_lead"},
    },
    {
        "id": "base-backend-engineer",
        "name": "Backend Engineer",
        "role": "backend_engineer",
        "runtimeMode": "cli",
        "allowedProviders": ["codex_cli", "claude_code_cli", "openhands", "swe_agent"],
        "allowedRuntimes": ["cli"],
        "allowedTools": ["shell", "workspace_patch", "evidence.create"],
        "allowedSkills": ["engineering-standards", "test-driven-development"],
        "permissionProfile": "dev_safe",
        "maxCostPerRun": 5.0,
        "maxTokensPerRun": 120000,
        "maxRuntimeSeconds": 1200,
        "requiresApprovalOverUsd": 2.0,
        "qualityGates": ["lint", "test", "typecheck", "build"],
        "defaultRuntimePolicy": {
            "providerCandidates": ["codex_cli", "claude_code_cli", "openhands", "swe_agent"],
            "requiredCapabilities": ["code_edit"],
            "selection": "first_executable",
            "fallback": "blocked_with_reason",
        },
        "reviewerPolicy": {"mode": "peer", "reviewerRole": "technical_lead"},
    },
    {
        "id": "base-frontend-engineer",
        "name": "Frontend Engineer",
        "role": "frontend_engineer",
        "runtimeMode": "cli",
        "allowedProviders": ["codex_cli", "claude_code_cli", "openhands", "swe_agent"],
        "allowedRuntimes": ["cli"],
        "allowedTools": ["shell", "workspace_patch", "evidence.create"],
        "allowedSkills": ["ui-ux-pro-max", "architecture-web", "test-driven-development"],
        "permissionProfile": "dev_safe",
        "maxCostPerRun": 5.0,
        "maxTokensPerRun": 120000,
        "maxRuntimeSeconds": 1200,
        "requiresApprovalOverUsd": 2.0,
        "qualityGates": ["lint", "test", "typecheck", "build", "accessibility"],
        "defaultRuntimePolicy": {
            "providerCandidates": ["codex_cli", "claude_code_cli", "openhands", "swe_agent"],
            "requiredCapabilities": ["code_edit"],
            "selection": "first_executable",
            "fallback": "blocked_with_reason",
        },
        "reviewerPolicy": {"mode": "peer", "reviewerRole": "technical_lead"},
    },
    {
        "id": "base-qa-engineer",
        "name": "QA Engineer",
        "role": "qa_engineer",
        "runtimeMode": "hybrid",
        "allowedProviders": ["codex_cli", "claude_code_cli", "openai_compatible"],
        "allowedRuntimes": ["cli", "api"],
        "allowedTools": ["shell", "evidence.create"],
        "allowedSkills": ["systematic-debugging", "test-driven-development"],
        "permissionProfile": "qa",
        "maxCostPerRun": 3.0,
        "maxTokensPerRun": 80000,
        "maxRuntimeSeconds": 900,
        "requiresApprovalOverUsd": 1.5,
        "qualityGates": ["test", "regression", "evidence_review"],
        "defaultRuntimePolicy": {
            "providerCandidates": ["codex_cli", "claude_code_cli", "openai_compatible"],
            "requiredCapabilities": ["chat"],
            "selection": "first_executable",
            "fallback": "blocked_with_reason",
        },
        "reviewerPolicy": {"mode": "peer", "reviewerRole": "technical_lead"},
    },
    {
        "id": "base-security-engineer",
        "name": "Security Engineer",
        "role": "security_engineer",
        "runtimeMode": "hybrid",
        "allowedProviders": ["claude_code_cli", "openai_compatible"],
        "allowedRuntimes": ["cli", "api"],
        "allowedTools": ["shell", "policy.evaluate", "evidence.create"],
        "allowedSkills": ["security-review", "codex-security:security-scan"],
        "permissionProfile": "qa",
        "maxCostPerRun": 5.0,
        "maxTokensPerRun": 120000,
        "maxRuntimeSeconds": 900,
        "requiresApprovalOverUsd": 2.0,
        "qualityGates": ["gitleaks", "semgrep", "security_scan"],
        "defaultRuntimePolicy": {
            "providerCandidates": ["claude_code_cli", "openai_compatible"],
            "requiredCapabilities": ["chat"],
            "selection": "first_executable",
            "fallback": "blocked_with_reason",
        },
        "reviewerPolicy": {"mode": "gated", "reviewerRole": "technical_lead"},
    },
    {
        "id": "base-devops-engineer",
        "name": "DevOps Engineer",
        "role": "devops_engineer",
        "runtimeMode": "cli",
        "allowedProviders": ["codex_cli", "claude_code_cli"],
        "allowedRuntimes": ["cli"],
        "allowedTools": ["shell", "evidence.create"],
        "allowedSkills": ["devops", "git-workflow"],
        "permissionProfile": "dev_safe",
        "maxCostPerRun": 4.0,
        "maxTokensPerRun": 90000,
        "maxRuntimeSeconds": 900,
        "requiresApprovalOverUsd": 2.0,
        "qualityGates": ["build", "deploy_dry_run", "rollback_plan"],
        "defaultRuntimePolicy": {
            "providerCandidates": ["codex_cli", "claude_code_cli"],
            "requiredCapabilities": ["chat"],
            "selection": "first_executable",
            "fallback": "blocked_with_reason",
        },
        "reviewerPolicy": {"mode": "gated", "reviewerRole": "technical_lead"},
    },
    {
        "id": "base-researcher",
        "name": "Researcher",
        "role": "researcher",
        "runtimeMode": "api",
        "allowedProviders": ["openai_compatible", "openrouter", "nvidia_nim", "anthropic_api"],
        "allowedRuntimes": ["api"],
        "allowedTools": ["mcp", "evidence.create"],
        "allowedSkills": ["research", "deep-research"],
        "permissionProfile": "plan",
        "maxCostPerRun": 4.0,
        "maxTokensPerRun": 100000,
        "maxRuntimeSeconds": 900,
        "requiresApprovalOverUsd": 2.0,
        "qualityGates": ["citation_check", "source_policy", "conflict_review"],
        "defaultRuntimePolicy": {
            "providerCandidates": ["openai_compatible", "openrouter", "nvidia_nim", "anthropic_api"],
            "requiredCapabilities": ["chat"],
            "selection": "first_executable",
            "fallback": "blocked_with_reason",
        },
        "reviewerPolicy": {"mode": "peer", "reviewerRole": "technical_lead"},
    },
    {
        "id": "base-release-manager",
        "name": "Release Manager",
        "role": "release_manager",
        "runtimeMode": "hybrid",
        "allowedProviders": ["claude_code_cli", "codex_cli"],
        "allowedRuntimes": ["cli"],
        "allowedTools": ["shell", "evidence.create", "policy.evaluate"],
        "allowedSkills": ["git-workflow", "verification-before-completion"],
        "permissionProfile": "release",
        "maxCostPerRun": 3.0,
        "maxTokensPerRun": 80000,
        "maxRuntimeSeconds": 900,
        "requiresApprovalOverUsd": 1.5,
        "qualityGates": ["release_checklist", "rollback_plan", "git_diff_check"],
        "defaultRuntimePolicy": {
            "providerCandidates": ["claude_code_cli", "codex_cli"],
            "requiredCapabilities": ["chat"],
            "selection": "first_executable",
            "fallback": "blocked_with_reason",
        },
        "reviewerPolicy": {"mode": "gated", "reviewerRole": "technical_lead"},
    },
)


def bootstrap_base_team_if_needed(connection: sqlite3.Connection) -> list[dict[str, Any]]:
    """Create the base active team only when the DB has no active agent profiles."""
    active = connection.execute(
        "SELECT COUNT(*) AS total FROM agent_profiles WHERE status = 'active'"
    ).fetchone()
    if int(active["total"] or 0) > 0:
        return []
    repository = AgentsRepository(connection)
    return [repository.upsert_agent_profile(profile) for profile in BASE_TEAM_PROFILES]
