import { copyFile, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { build } from 'esbuild';

const rootDir = resolve('local-control-center');
const outdir = resolve(rootDir, 'dist');
const webOutdir = resolve(outdir, 'web');
const webAssetsOutdir = resolve(webOutdir, 'assets');
const designSystemDir = resolve(rootDir, 'web/src/design-system');
const cssFiles = ['tokens.css', 'base.css', 'layout.css', 'components.css', 'motion.css'];

await rm(outdir, { recursive: true, force: true });
await mkdir(outdir, { recursive: true });
await mkdir(webAssetsOutdir, { recursive: true });

await build({
	entryPoints: [resolve(rootDir, 'web/dashboard-client.jsx')],
	outfile: resolve(webAssetsOutdir, 'dashboard.js'),
	bundle: true,
	alias: {
		'react-dom/client': resolve('node_modules/react-dom/client.js'),
	},
	format: 'esm',
	platform: 'browser',
	target: ['chrome120', 'firefox120', 'safari17'],
	define: {
		'process.env.NODE_ENV': '"production"',
	},
	minify: true,
	sourcemap: false,
	logLevel: 'info',
	jsx: 'automatic',
	loader: {
		'.jsx': 'jsx',
	},
});

await Promise.all([
	copyFile(resolve(rootDir, 'web/index.html'), resolve(webOutdir, 'index.html')),
]);

const cssBundle = await Promise.all(cssFiles.map((file) => readFile(resolve(designSystemDir, file), 'utf8')));
await writeFile(
	resolve(webOutdir, 'dashboard.css'),
	`/* Generated by local-control-center/build.mjs. Source: web/src/design-system/*.css */\n${cssBundle.join('\n\n')}`,
	'utf8',
);
