from __future__ import annotations

from typing import Any, Protocol


class OverviewStore(Protocol):
    cwd: Any

    def ensure_runtime_project(self) -> dict[str, Any]: ...
    def ensure_workspace_state(self, cwd: Any = None) -> dict[str, Any]: ...
    def list_project_templates(self) -> list[dict[str, Any]]: ...
    def list_projects(self) -> list[dict[str, Any]]: ...
    def list_providers(self) -> list[dict[str, Any]]: ...
    def list_teams(self) -> list[dict[str, Any]]: ...
    def list_agents(self) -> list[dict[str, Any]]: ...
    def list_sessions(self) -> list[dict[str, Any]]: ...
    def list_jobs(self) -> list[dict[str, Any]]: ...
    def list_job_runs(self) -> list[dict[str, Any]]: ...
    def list_events(self) -> list[dict[str, Any]]: ...
    def list_audit_events(self) -> list[dict[str, Any]]: ...
    def list_memory_items(self) -> list[dict[str, Any]]: ...
    def list_prompt_templates(self) -> list[dict[str, Any]]: ...
    def list_action_requests(self) -> list[dict[str, Any]]: ...
    def list_ide_connections(self) -> list[dict[str, Any]]: ...
    def list_workflows(self) -> list[dict[str, Any]]: ...
    def list_workflow_runs(self) -> list[dict[str, Any]]: ...
    def list_workflow_steps(self) -> list[dict[str, Any]]: ...
    def list_permission_decisions(self) -> list[dict[str, Any]]: ...
    def list_evidence_packages(self) -> list[dict[str, Any]]: ...
    def list_agent_profiles(self) -> list[dict[str, Any]]: ...
    def list_model_policies(self) -> list[dict[str, Any]]: ...
    def list_agent_tool_calls(self) -> list[dict[str, Any]]: ...
    def list_model_calls(self) -> list[dict[str, Any]]: ...
    def list_cost_usage(self) -> list[dict[str, Any]]: ...
    def list_runtime_workspaces(self) -> list[dict[str, Any]]: ...
    def list_skills(self) -> list[dict[str, Any]]: ...
    def list_architecture_decisions(self) -> list[dict[str, Any]]: ...
    def list_risks(self) -> list[dict[str, Any]]: ...
    def list_next_steps(self) -> list[dict[str, Any]]: ...


def build_overview(store: OverviewStore) -> dict[str, Any]:
    store.ensure_runtime_project()
    workspace_state = store.ensure_workspace_state(store.cwd)
    return {
        "projectTemplates": store.list_project_templates(),
        "projects": store.list_projects(),
        "providers": store.list_providers(),
        "teams": store.list_teams(),
        "agents": store.list_agents(),
        "sessions": store.list_sessions(),
        "jobs": store.list_jobs(),
        "jobRuns": store.list_job_runs(),
        "events": store.list_events(),
        "auditEvents": store.list_audit_events(),
        "memoryItems": store.list_memory_items(),
        "promptTemplates": store.list_prompt_templates(),
        "actionRequests": store.list_action_requests(),
        "ideConnections": store.list_ide_connections(),
        "workflows": store.list_workflows(),
        "workflowRuns": store.list_workflow_runs(),
        "workflowSteps": store.list_workflow_steps(),
        "permissionDecisions": store.list_permission_decisions(),
        "evidencePackages": store.list_evidence_packages(),
        "agentProfiles": store.list_agent_profiles(),
        "modelPolicies": store.list_model_policies(),
        "modelProviders": store.list_providers(),
        "agentToolCalls": store.list_agent_tool_calls(),
        "modelCalls": store.list_model_calls(),
        "costUsage": store.list_cost_usage(),
        "runtimeWorkspaces": store.list_runtime_workspaces(),
        "skills": store.list_skills(),
        "architectureDecisions": store.list_architecture_decisions(),
        "riskRegister": store.list_risks(),
        "nextSteps": store.list_next_steps(),
        "workspaceState": workspace_state["state"],
        "workspaceStateMetadata": workspace_state["metadata"],
        "openDesign": {"status": "python-backend"},
        "security": {"loopbackOnly": True, "writeTokenRequired": True},
    }
